version: '3'
services:

    bot:
      build: .
      command: python main.py
      ports:
        - "5000:5000"
      env_file:
        - ./docker-config/flavors/variables.env
      volumes:
        - ./web/:/home/docker/slackbot/

    redis:
      container_name: cache
      image: redis

